`timescale 1ns / 1ps

/*
 * Five-bit processor flag register.
 *
 *     stored_flags[4] = C, Carry
 *     stored_flags[3] = L, Unsigned Less Than
 *     stored_flags[2] = N, Signed Less Than
 *     stored_flags[1] = F, Overflow
 *     stored_flags[0] = Z, Zero or Equal
 *
 * Each flag has its own write-enable bit
 * A disabled flag keeps its previous value
 */
module FlagRegister (

    input wire clk,
    input wire reset,

    // New flags generated by the ALU
    input wire [4:0] new_flags,

    // Selects which flag bits are updated
    input wire [4:0] flag_write_enable,

    // Flags currently stored in the processor status register
    output reg [4:0] stored_flags
);

    /*
     * The flags are stored on the rising clock edge.
     *
     * Reset is asynchronous and active high.
     */
    always @(posedge clk or posedge reset) begin

        if (reset) begin

            stored_flags <= 5'b00000;

        end
        else begin

            // Update Carry only when its enable is 1
            if (flag_write_enable[4] == 1'b1)
                stored_flags[4] <= new_flags[4];

            // Update Unsigned Less Than only when enabled
            if (flag_write_enable[3] == 1'b1)
                stored_flags[3] <= new_flags[3];

            // Update Signed Less Than only when enabled
            if (flag_write_enable[2] == 1'b1)
                stored_flags[2] <= new_flags[2];

            // Update Overflow only when enabled
            if (flag_write_enable[1] == 1'b1)
                stored_flags[1] <= new_flags[1];

            // Update Zero or Equal only when enabled
            if (flag_write_enable[0] == 1'b1)
                stored_flags[0] <= new_flags[0];

        end

    end

endmodule